apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
images:
  - name: nourhenhachem/innodeploy-app
    newTag: v1.0.3
    newName: nourhenhachem/innodeploy-app
