apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: nourhenhachem/innodeploy-app
    newTag: v1778074256
    newName: nourhenhachem/innodeploy-app
