apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: innodeploy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hachemn/innodeploy-gitops.git
    targetRevision: main
    path: apps/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
